import { MigrationInterface, QueryRunner } from 'typeorm';

export class createUserTable1649603104745 implements MigrationInterface {
  name = 'createUserTable1649603104745';
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        create table users (
            id int generated by default as identity primary key,
            name varchar(150) not null,
            email varchar(150) not null,
            password varchar not null,
            created_at timestamptz not null,
            updated_at timestamptz not null
          )
        `);
    await queryRunner.query(
      `grant select, insert, update, delete on table users to migrator`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `REVOKE SELECT, INSERT, UPDATE, DELETE ON users FROM migrator`,
    );
    await queryRunner.query(`DROP TABLE users`);
  }
}
