import { MigrationInterface, QueryRunner } from 'typeorm';

export class createMailTable1651567886129 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        create table mails (
            id int generated by default as identity primary key,
            uuid varchar(150) not null,
            content varchar(150) not null,
            receiver_email varchar not null,
            subject varchar(150) not null,
            sent_at varchar not null,
            status varchar not null,
            type varchar not null,
            created_at timestamptz not null,
            updated_at timestamptz not null
          )
        `);
    await queryRunner.query(
      `grant select, insert, update, delete on table mails to migrator`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `REVOKE SELECT, INSERT, UPDATE, DELETE ON mails FROM migrator`,
    );
    await queryRunner.query(`DROP TABLE mails`);
  }
}
