import { MigrationInterface, QueryRunner } from 'typeorm';

export class createMailTemplatesTable1652108738628
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    // NOTE: do not forget to run this command with super-user permission
    // await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`);
    await queryRunner.query(`
            create table templates (
                id int generated by default as identity primary key,
                uuid uuid DEFAULT uuid_generate_v4 () not null,
                key varchar(150) not null,
                status varchar(150) not null,
                created_at timestamptz not null,
                updated_at timestamptz not null,
                CONSTRAINT key_unique UNIQUE (key)
              )
            `);
    await queryRunner.query(
      `grant select, insert, update, delete on table mails to migrator`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `REVOKE SELECT, INSERT, UPDATE, DELETE ON mails FROM migrator`,
    );
    await queryRunner.query(`DROP TABLE mails`);
  }
}
